### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by Vlada31R** [unsplash/unsplash-photopicker-ios#16]
Hi, tell me please, would you add dark mode support or I should manage it in my code? Thanks

**Comment by ocollet** [comment]
We'll work on it next week.

**Comment by ocollet** [comment]
@Vlada31R We released [v1.1.0](https://github.com/unsplash/unsplash-photopicker-ios/releases/tag/1.1.0) yesterday that adds support for iOS 13, including dark mode.

**Comment by Vlada31R** [comment]
Thank you very much))
