### ISSUE TITLE
Display and Search of Specific collections

### ISSUE THREAD

**Issue by ahamedsaifudeen** [unsplash/unsplash-photopicker-ios#18]
It would be great if this component has option to list and search within one or more collections (created by the account of the API account).

**Comment by ocollet** [comment]
@ahamedsaifudeen Such option would potentially seriously limit the amount of content available for the end-users, so we won't add the option.

You can always fork the repository and do it yourself, just make sure to follow our [API guidelines](https://unsplash.com/documentation#guidelines--crediting).
