### ISSUE TITLE
Get the image attached to the UnsplashPicker collection cell without unlocking the pod

### ISSUE THREAD

**Issue by SocialKitLtd** [unsplash/unsplash-photopicker-ios#20]
Is it possible to get the direct UIImageView UIImage from the UICollectionView cell when passing the UnsplashPickerDelegate? Instead of the need to re-create it from the URL from the UnsplashPhoto object?

**Comment by ocollet** [comment]
@CraftizLtd The image used in the `UIImageView` is a variant scaled to match the `UIImageView`'s size, so there isn't much you can do with it other than use it for a low-res preview.

What would be the use case?

**Comment by ocollet** [comment]
Closing: no answer and the user has deleted their account.
