### ISSUE TITLE
Add support for SwiftUI

### ISSUE THREAD

**Issue by lisindima** [unsplash/unsplash-photopicker-ios#21]
Add support for SwiftUI

**Comment by ocollet** [comment]
@lisindima I have yet to dive into SwiftUI, so I'm not sure I understand the issue.

1. Do you mean that you'd like the component to be built with SwiftUI?
2. Do you mean the component cannot be used in a SwiftUI project?
3. What would be required to add support?

**Comment by lisindima** [comment]
Thanks for the answer, I would like to see instructions on how to run this component in swiftui, I'm not sure if this can be done using UIViewControllerRepresentable

**Comment by ocollet** [comment]
Makes sense, I will see if I can test it this week.

**Comment by lisindima** [comment]
Hi, I was able to run this component on SwiftUI and it works fine)
`i
struct UnsplashImagePicker: UIViewControllerRepresentable {
    
    let configuration = UnsplashPhotoPickerConfiguration(
      accessKey: "",
      secretKey: ""
    )
    
    func makeUIViewController(context: UIViewControllerRepresentableContext<UnsplashImagePicker>) -> UnsplashPhotoPicker {
        let unsplashImagePicker = UnsplashPhotoPicker(configuration: configuration)
        return unsplashImagePicker
    }
        
    func makeCoordinator() -> UnsplashImagePicker.Coordinator {
        return Coordinator(self)
    }
        
    class Coordinator: NSObject, UIImagePickerControllerDelegate, UINavigationControllerDelegate {
        var parent: UnsplashImagePicker
        init(_ parent: UnsplashImagePicker) {
            self.parent = parent
        }
            
        func unsplashPhotoPicker(_ photoPicker: UnsplashPhotoPicker, didSelectPhotos photos: [UnsplashPhoto]) {
            
        }
    }
        
    func updateUIViewController(_ uiViewController: UnsplashPhotoPicker, context: UIViewControllerRepresentableContext<UnsplashImagePicker>) {
            
    }
}
`

**Comment by lisindima** [comment]
and yet there is a problem with this code, the unsplashPhotoPicker function does not work completely, respectively, it is not possible to select an image and nil always returns

**Comment by ocollet** [comment]
Great! Thank you for taking a shot at it! 👏
