### ISSUE TITLE
Question about using this framework

### ISSUE THREAD

**Issue by mfcollins3** [unsplash/unsplash-photopicker-ios#26]
I am looking to integrate Unsplash into an app that I am building. However, this library seems to be contradictory to Unsplash’s API guidelines. Specifically, item 4 at https://help.unsplash.com/en/articles/2511245-unsplash-api-guidelines says that the access key and secret key cannot be embedded in the application, yet they are requirements to use this framework.

Is this framework not intended to be used in published applications?

**Comment by ocollet** [comment]
Hi Michael, thanks for checking this out. This guideline is meant for web projects and does not apply to iOS apps. We will update the guidelines.

So you're good to integrate the framework into your app, that's what it's for.
