### ISSUE TITLE
API misuse

### ISSUE THREAD

**Issue by puelocesar** [unsplash/unsplash-photopicker-ios#39]
When using this Library, everything seems to work fine, but I'm getting dozens of messages like this on the console:

```
2020-11-17 09:57:18.377493+0100 MyProject[17854:197368] [logging] misuse at line 130558 of [02c344acea]
2020-11-17 09:57:18.377694+0100 MyProject[17854:197368] [logging] API call with unopened database connection pointer
```

Should I worry about having problems with Unsplash? They say they can ban my account if I'm misusing the API

**Comment by ocollet** [comment]
@puelocesar This message is not related to the Unsplash API, so don't worry we won't ban your account for this. The message seems related to SQLite.

**Comment by Kondamon** [comment]
This is related to https://github.com/unsplash/unsplash-photopicker-ios/issues/35 and is still an issue.
