### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by pzmudzinski** [unsplash/unsplash-photopicker-ios#52]
There are open Pull Requests without any response, the same with issues.

**Comment by pzmudzinski** [comment]
I guess not lol ( ˘︹˘ )

**Comment by ocollet** [comment]
Sorry about that. I'm the only developer in charge of all our native apps at Unsplash. I'm currently finishing up an update to our iOS app and will jump on this repo right after to give it some much-needed ❤️.

**Comment by ocollet** [comment]
I just went through the pull requests. I'll make sure to check the project more frequently in the future.
