### ISSUE TITLE
Photo Picker Configuration on Obj-C

### ISSUE THREAD

**Issue by Elvereth** [unsplash/unsplash-photopicker-ios#53]
Hello,
maybe I'm missing something, but I'm trying to integrate the Unsplash Photo Picker in my native app written in **Objective C**.

I've imported the framework using CocoaPods and that creates the `UnsplashPhotoPicker.h` header in my project.
I can import it in my UIViewController, but I am unable to configurate the picker with the relevant information (accessKey, secretKey, etc.).
In Objective C it only allows me to call the basic initialization
`UnsplashPhotoPicker *picker = [[UnsplashPhotoPicker alloc] init];`
but it then throws an error on this line, saying
`UnsplashPhotoPicker/UnsplashPhotoPicker.swift:31: Fatal error: Use of unimplemented initializer 'init(nibName:bundle:)' for class 'UnsplashPhotoPicker.UnsplashPhotoPicker'`

I don't know how to proceed. What am I missing here?
I don't know how to correctly call the configuration method using Objective C.

@ocollet any suggestions on how to fix it?

Thanks

**Comment by ocollet** [comment]
Hi @Elvereth,

Unfortunately, the component does not support Objective-C. It's been a while since we took the decision, so I don't remember precisely why. I think it was because we're using some Swift syntax that is incompatible with Objective-C.

I'm sorry about that.
