### ISSUE TITLE
Last page (empty result) will force UI into empty result state

### ISSUE THREAD

**Issue by kylestew** [unsplash/unsplash-photopicker-ios#8]
https://github.com/unsplash/unsplash-photopicker-ios/blob/cd99924f795dd7cb86d412e3f6315582764e1104/UnsplashPhotoPicker/UnsplashPhotoPicker/Classes/Controllers/UnsplashPhotoPickerViewController.swift#L338

A user will scroll to the end of the search results, scroll back up and the search results will disappear saying "no results". Need to reference the entire result set here instead of just the latest.

**Comment by nicol3a** [comment]
#9

**Comment by kylestew** [comment]
That solves it!
